# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: build plugin installer
  inputs:
    targetType: 'inline'
    script: |
      $DistTool = $(Build.SourcesDirectory)\utils\DistributionTool.exe
      $ReleaseDir = $(Build.SourcesDirectory)\src\bin\Release\au.com.mullineaux.lifx.sdPlugin
      & $env:comspec "/c $DistTool --build --input  $ReleaseDir --output $(Build.ArtifactStagingDirectory)"

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'

# - task: GitHubRelease@1
#   displayName: Create Github Release
#   inputs:
#     gitHubConnection: 'github.com/caseymullineaux'
#     repositoryName: '$(Build.Repository.Name)'
#     action: 'create'
#     target: '$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     changeLogCompareToRelease: 'lastFullRelease'
#     changeLogType: 'commitBased'
